config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#top'

  resources :users do
    resources :relationships, only: [:create, :destroy]
      member do
        get :follows
        get :followers
      end
  end

  resources :tweets do
    collection do
      get :comment_tweets
      get :follows
      get :likes
      get :mytweets
      get :top
    end

    resources :comments, only: [:create, :edit, :update, :destroy]
    resource :likes,     only: [:create, :destroy]
  end

  resources :groups,     only: [:new, :create, :update, :destroy] do
    resources :messages, only: [:index, :create, ]
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :place

  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :comments, dependent: :delete_all
  has_many :comment_users, through: :comments, source: :user
  has_many :likes, dependent: :delete_all
  has_many :like_users, through: :likes, source: :user
  
  # current_userがいいねしているかどうかを判定してくれる
  def like_by?(user)
    likes.where(user_id: user.id).exists?
  end

  validates :tweet,       presence: true, length: {maximum: 300}
  validates :user_id,     presence: true
  validates :place_id,    presence: true
  validates :category_id, presence: true
  validates :food,        presence: true, length: {maximum: 30}
  validates :price,       presence: true, length: {maximum: 8}, numericality: true
  validates :store,       presence: true, length: {maximum: 30}
  validates :image,       presence: true
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :move_to_signup, only: [:new, :create, :edit, :update, :destroy]
  before_action :tweet_find, only: [:show, :edit, :update, :destroy, ]
  before_action :user_find, only: [:follows, :likes, :mytweets, :comment_tweets]

  def top
    @tweets = Tweet.order("created_at DESC").limit(8)
    @users = User.order("created_at DESC").limit(8)
  end
  
  def index
    @tweets = Tweet.order("created_at DESC").page(params[:page]).per(50)
    @tweetss = Tweet.where('tweet LIKE(?)', "%#{params[:keyword]}%")
    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    if @tweet.save
      redirect_to tweet_path(@tweet.id)
    else
      render action: :new
    end
  end

  def show
    @comments = @tweet.comments
    @comment = Comment.new
  end

  def edit
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to tweet_path(@tweet.id)
    else
      render action: :new
    end
  end

  def destroy
    if @tweet.destroy
      redirect_to user_path(current_user.id)
    else
      redirect_to root_path
    end
  end

  def follows
    @finduser = User.find(current_user.id)
    @follows = @finduser.followings
    @FolTws = Tweet.where(user_id: @follows.ids).order("created_at DESC").page(params[:page]).per(10)
  end

  def likes
    @likes = @user.likes
    @LikTws = @likes.map{|like| Tweet.find(like.tweet_id)}
    @LikTws = Kaminari.paginate_array(@LikTws).page(params[:page]).per(50)
  end

  def mytweets
    @mytweets = Tweet.where(user_id: params[:format]).order("created_at DESC").page(params[:page]).per(50)
  end

  def comment_tweets
    @comments = @user.comments
    @comment_tweets = @comments.map{|comment| Tweet.find(comment.tweet_id)}
    @comment_tweets = Kaminari.paginate_array(@comment_tweets).page(params[:page]).per(50)
  end

  private
  
  def tweet_params
    params.require(:tweet).permit(:tweet, :user_id, :place_id, :category_id, :food, :price, :store, :image)
  end
  
  def tweet_find
    @tweet = Tweet.find(params[:id])
  end

  def user_find
    @user = User.find(params[:format])
  end
  
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/comment_tweets.html.haml
.contener
  .food-contener
    .food-title-contener
      .food-title-contener__title
        %p コメントしたTweets
    %ul.tweets-list
      =render partial: "shared/tweets", collection: @comment_tweets, as: :tweet
    =paginate @comment_tweets

app/views/tweets/edit.html.haml
.contener
  %h2.contener__title Edit Tweet
  - if @tweet.errors.any?
    %ul.error-title エラー！
    - @tweet.errors.full_messages.each do |message|
      %li=message
  =form_with model: @tweet, class: "new", local: true do |f|
    .field
      =f.label :image
      =f.file_field :image, autofocus: true, autocomplete: "image"
      -if @tweet.image
        = image_tag @tweet.image.url, class: "image-preview"
    .field
      =f.label :food
      =f.text_area :food, autofocus: true, rows: 1, cols: 50, placeholder: "30文字以内"
    .field
      =f.label :price
      =f.text_area :price, autofocus: true, rows: 1, cols: 50, placeholder: "8桁以内"
    .field
      =f.label :place_id
      =f.collection_select :place_id, Place.all, :id, :name, prompt: true
    .field
      =f.label :category_id
      =f.collection_select :category_id, Category.all, :id, :name, prompt: true
    .field
      =f.label :tweet
      =f.text_area :tweet, autofocus: true, rows: 5, cols: 50, placeholder: "300文字以内"
    .actions
      =f.submit "send", class: "actions__btn"
      =link_to "BACK", :back, class: "actions__back"

    

app/views/tweets/follows.html.haml
.show-contener  
  =render "shared/sidebar"
  .food-contener
    .food-title-contener
      .food-title-contener__title
        %p フォローした人のTweets
    %ul.tweets-list
      =render partial: "shared/tweets", collection: @FolTws, as: :tweet
    =paginate @FolTws

app/views/tweets/index.html.haml
.contener
  .food-contener
    .food-form-contener
      =form_with url: tweets_path, method: :get, local: true do |f|
        =f.label :search
        =f.text_field :search ,class: "search-form"
    .food-title-contener
      .food-title-contener__title
        %p New Tweets
    %ul.tweets-list
      =render partial: "shared/tweets", collection: @tweets, as: :tweet
    =paginate @tweets

app/views/tweets/likes.html.haml
.contener
  .food-contener
    .food-title-contener
      .food-title-contener__title
        %p いいねしたTweets
    %ul.tweets-list
      =render partial: "shared/tweets", collection: @LikTws, as: :tweet
    =paginate @LikTws

app/views/tweets/mytweets.html.haml
.contener
  .food-contener
    .food-title-contener
      .food-title-contener__title
        %p 自分のTweets
    %ul.tweets-list
      =render partial: "shared/tweets", collection: @mytweets, as: :tweet
    =paginate @mytweets

app/views/tweets/new.html.haml
.contener
  .left-contener
    %h2.contener__title New Tweet
    - if @tweet.errors.any?
      %ul.error-title エラー！
      - @tweet.errors.full_messages.each do |message|
        %li=message
    =form_with model: @tweet, class: "form-contener__form", local: true do |f|
      .field
        =f.label :image
        =f.file_field :image, autofocus: true, autocomplete: "image"
      .field
        =f.label :food
        =f.text_area :food, autofocus: true, rows: 1, cols: 50, placeholder: "30文字以内"
      .field
        =f.label :store
        =f.text_area :store, autofocus: true, rows: 1, cols: 50, placeholder: "30文字以内"
      .field
        =f.label :price
        =f.text_area :price, autofocus: true, rows: 1, cols: 50, placeholder: "8桁以内"
      .field
        =f.label :place_id
        =f.collection_select :place_id, Place.all, :id, :name, prompt: true
      .field
        =f.label :category_id
        =f.collection_select :category_id, Category.all, :id, :name, prompt: true
      .field
        =f.label :tweet
        =f.text_area :tweet, autofocus: true, rows: 5, cols: 50, placeholder: "300文字以内"
      .actions
        =f.submit "SEND", class: "actions__send"
        =link_to "BACK", :back, class: "actions__back"

app/views/tweets/show.html.haml
.contener
  .DtlFood-contener
    .DtlFood-title-contener
    .DtlFood-contents-contener
      .DtlFood-image-section
        .DtlFood-image-section__main
          =image_tag @tweet.image.url, class: "image-section__main--size" 
      
      .DtlFood-detail-section
        -if user_signed_in? && @tweet.user_id == current_user.id
          .DelEdits-area
            =link_to edit_tweet_path, class: "DelEdits-area--edit" do
              =icon 'fas', 'pen-square'
            =link_to tweet_path(@tweet.id), method: :delete, class: "DelEdits-area--delete" do
              =icon 'far', 'trash-alt'
        .DelFood-area
          .DelFood-area__store
            =@tweet.store
          .DelFood-area__name
            =@tweet.food
          .DelFood-area__price
            =@tweet.price
            %span.font-size 円
        .DelTweet-area
          =@tweet.tweet

        .DelContents-area
          %div{id:"contents-area__mark_#{@tweet.id}"}
            =render partial: 'likes/like', locals: {tweet: @tweet} 

    .DtlFood-CmtTil-contener
      .DtlFood-CmtTil-section
        %p Comment
    
    .DtlFood-CmtFom-contener
      -if user_signed_in?
        .DtlFood-CmtFom-section
          =form_with model:[@tweet, @comment], local: true do |f|
            .CmtFomField-area
              =f.label :comment
              =f.text_area :comment, rows: "5", cols: "50", placeholder: "200文字以内"
            .CmtFomAct-area
              =f.submit "send", class: "CmtFomAct-area__btn"

    .DtlFood-CmtContents-contener
      %ul.comments-list
        -@comments.each do |comment|
          %li.comment-post
            .DelFoCom-UserSection
              .DelFoCom-UserSection__detail
                =link_to (image_tag "#{comment.user.avater.url}", alt: "", class: "DelFoCom-UserSection__detail--size"), "/users/#{comment.user_id}"
                =link_to "#{comment.user.name}", "/users/#{comment.user_id}", class:"DelFoCom-UserSection__detail--font"
            .DelFoCom-TextSection
              .DelFoCom-TextSection__comment
                =comment.comment
              -if user_signed_in? && comment.user_id == current_user.id
                .DelFoCom-TextSection__edits
                  =link_to tweet_comment_path(comment.tweet_id, comment.id), method: :delete, class: "DelFoCom-TextSection__edits--delete" do
                    =icon 'fas', 'trash-alt'
                  =link_to edit_tweet_comment_path(comment.tweet_id, comment.id), class: "DelFoCom-TextSection__edits--edit" do
                    =icon 'fas', 'pen-square'

app/views/tweets/top.html.haml
.contener
  .food-contener
    .food-title-contener
      .food-title-contener__title
        %p New Tweets
    %ul.tweets-list
      =render partial: "shared/tweets", collection: @tweets, as: :tweet
    .more-contener
      =link_to "more", tweets_path, class: "more-contener__more"

  .user-contener
    .user-title-contener
      .user-title-contener__title
        %p New Users
    %ul.users-list
      =render partial: "shared/users", collection: @users, as: :user
    .more-contener
      =link_to "more", users_path, class: "more-contener__more"
    
  