config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#top'

  resources :users do
    resources :relationships, only: [:create, :destroy]
      member do
        get :follows
        get :followers
      end
  end

  resources :tweets do
    collection do
      get :comment_tweets
      get :follows
      get :likes
      get :mytweets
      get :top
    end

    resources :comments, only: [:create, :edit, :update, :destroy]
    resource :likes,     only: [:create, :destroy]
  end

  resources :groups,     only: [:new, :create, :update, :destroy] do
    resources :messages, only: [:index, :create, ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    {id: 1, name: '寿司・魚料理'},
    {id: 2, name: '和食・日本料理'},
    {id: 3, name: 'ラーメン・麺類'},
    {id: 4, name: '丼もの・揚げ物'},
    {id: 5, name: 'お好み焼き・粉物'},
    {id: 6, name: 'アジア・エスニック'},
    {id: 7, name: '中華'},
    {id: 8, name: 'アメリカ料理'},
    {id: 9, name: 'アフリカ料理'},
    {id: 10, name: 'その他各国の料理'},
    {id: 11, name: '肉料理'},
    {id: 12, name: '焼き鳥・串料理'},
    {id: 13, name: '鍋'},
    {id: 14, name: '居酒屋・バー'},
    {id: 15, name: 'カフェ・スイーツ'},
    {id: 16, name: 'ファミレス・ファーストフード'},
    {id: 17, name: 'ビュッフェ・バイキング'},
    {id: 18, name: 'その他'},
  ]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :comment,    presence: true, length: {maximum: 200}
  validates :tweet_id,   presence: true
  validates :user_id,    presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :messages, dependent: :delete_all
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :tweet_id,   presence: true
  validates :user_id,    presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/place.rb
class Place < ActiveHash::Base
  self.data = [
    {id: 1, name: '都島区'},
    {id: 2, name: '福島区'},
    {id: 3, name: '此花区'},
    {id: 4, name: '西区'},
    {id: 5, name: '港区'},
    {id: 6, name: '大正区'},
    {id: 7, name: '天王寺区'},
    {id: 8, name: '浪速区'},
    {id: 9, name: '西淀川区'},
    {id: 10, name: '東淀川区'},
    {id: 11, name: '東成区'},
    {id: 12, name: '生野区'},
    {id: 13, name: '旭区'},
    {id: 14, name: '城東区'},
    {id: 15, name: '阿倍野区'},
    {id: 16, name: '住吉区'},
    {id: 17, name: '東住吉区'},
    {id: 18, name: '西成区'},
    {id: 19, name: '淀川区'},
    {id: 20, name: '鶴見区'},
    {id: 21, name: '住之江区'},
    {id: 22, name: '平野区'},
    {id: 23, name: '北区'},
    {id: 24, name: '中央区'},
    {id: 25, name: '大阪その他'},
  ]
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :place

  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :comments, dependent: :delete_all
  has_many :comment_users, through: :comments, source: :user
  has_many :likes, dependent: :delete_all
  has_many :like_users, through: :likes, source: :user
  
  # current_userがいいねしているかどうかを判定してくれる
  def like_by?(user)
    likes.where(user_id: user.id).exists?
  end

  validates :tweet,       presence: true, length: {maximum: 300}
  validates :user_id,     presence: true
  validates :place_id,    presence: true
  validates :category_id, presence: true
  validates :food,        presence: true, length: {maximum: 30}
  validates :price,       presence: true, length: {maximum: 8}, numericality: true
  validates :store,       presence: true, length: {maximum: 30}
  validates :image,       presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  mount_uploader :avater, AvaterUploader

  has_many :comments,     dependent: :delete_all
  has_many :messages,     dependent: :delete_all
  has_many :tweets,       dependent: :delete_all

  has_many :likes,        dependent: :delete_all
  has_many :like_tweets,  through: :likes, source: :tweet

  has_many :active_relationships,  class_name: "Relationship", foreign_key: :following_id
  has_many :followings,            through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers,             through: :passive_relationships, source: :following

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  validates :name,    presence: true, length: {maximum: 8}
  validates :profile, length: {maximum: 300}
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :move_to_signup

  def create
    @tweet = Tweet.find(params[:tweet_id])
    like = current_user.likes.new(tweet_id: params[:tweet_id])
    like.save!
  end

  def destroy
    @tweet = Tweet.find(params[:tweet_id])
    like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    like.destroy
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_find, except: [:index]
  
  def index
    @users = User.order("created_at DESC").page(params[:page]).per(40)
    @userss = User.where('name LIKE(?)', "%#{params[:keyword]}%")
    respond_to do |format|
      format.html
      format.json
    end
  end

  def show
    @follows = @user.followings
    @followsTws = Tweet.where(user_id: @follows.ids).order("created_at DESC").limit(50)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(current_user.id)
    else
      redirect_to root_path
    end
  end

  def follows
    @follows = @user.followings
    @follows = Kaminari.paginate_array(@follows).page(params[:page]).per(40)
  end

  def followers
    @followers = @user.followers
    @followers = Kaminari.paginate_array(@followers).page(params[:page]).per(40)
  end

  private
  
  def user_params
    params.require(:user).permit(:avater, :name, :profile)
  end

  def user_find
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Tweetspace
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://fonts.googleapis.com/css?family=Lato:400,700|Noto+Sans+JP:400,700", :rel => "stylesheet"}/
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"}

    -# %script{:src => "/path/to/infinite-scroll.pkgd.min.js"}
  %body
    #wapper
      .header
        .header-left
          .header-left__title
            =link_to "/", class:"header-left__title--font" do
              %p OSAKA
              %P LUNCH

        .header-right
          .header-right__contents
            =link_to "みんなのTweet", tweets_path, class: "header-right__contents--tweet" 

          -if user_signed_in?
            .header-right__posts
              =link_to "Tweet投稿", new_tweet_path, class: "header-right__posts--tweet" 
                
          
          .header-right__user-contents
            -if user_signed_in?
              =link_to "SIGN OUT", destroy_user_session_path, method: :delete, class: "header-right__user-contents--page"
              =link_to "MY PAGE", "/users/#{current_user.id}", class: "header-right__user-contents--page"
            -else
              =link_to "SIGN IN", new_user_session_path, class: "header-right__user-contents--page"
              =link_to "SIGN UP", new_user_registration_path, class: "header-right__user-contents--page"
                

      = yield
      
    .fotter
      .fotter__title
        =link_to "/", class:"fotter__title--font" do
          %p OSAKA
          %P LUNCH

app/views/shared/_sidebar.haml
.Sidebar-contener
  .Sidebar-user-section
    .UserAva-area
      .UserAva-area__detail
        =link_to (image_tag "#{@user.avater.url}", class: "UserAva-area__detail--size"), user_path(@user.id)
        =link_to "#{@user.name}", user_path(@user.id), class: "UserAva-area__detail--font"
      .UserAva-area__follow
        -if user_signed_in? && @user.id != current_user.id
          -if @user.followed_by?(current_user)
            =link_to "followed", user_relationship_path(@user.id), class: "profile-section__follow--font", method: :delete
          -else
            =link_to "follow", user_relationships_path(@user.id), class: "profile-section__follow--font", method: :post 
    .UserProf-area
      =@user.profile
    .UserFolw-area
      =link_to follows_user_path(@user.id), class: "UserFolw-area__follow" do
        follow:
        =@user.followings.count
      =link_to followers_user_path(@user.id), class: "UserFolw-area__follower" do
        follower:
        =@user.followers.count
    -if user_signed_in? && @user.id == current_user.id
      .UserEdit-area
        =link_to "プロフィールの編集", edit_user_path(@user.id), class: "UserEdit-area__edit"
    .UserTwt-area
      .UserTwt-area__title
        .UserTwt-area__title--font Tweet
      .UserTwt-area__link
        =link_to "#{@user.name}のTweet", mytweets_tweets_path(@user.id), class: "UserTwt-area__link--font"
        =link_to "いいねしたTweet", likes_tweets_path(@user.id), class: "UserTwt-area__link--font"
        =link_to "コメントしたTweet",comment_tweets_tweets_path(@user.id), class: "UserTwt-area__link--font"
          

app/views/shared/_tweets.html.haml
%li.tweet-post
  =link_to "", tweet_path(tweet.id), class: "link-section"
  .user-section
    .user-section__detail
      =link_to (image_tag "#{tweet.user.avater.url}", class: "user-section__detail--size"), user_path(tweet.user.id)
      =link_to "#{tweet.user.name}", user_path(tweet.user.id), class: "user-section__detail--font"
  .img-section
  -if tweet.image.url
    =image_tag tweet.image.url, class: "img-section__img"

  .detail-section
    .contents-area
      %div{id:"contents-area__mark_#{tweet.id}"}
        =render partial: 'likes/like', locals: {tweet: tweet} 
      .contents-area__date 
        .contents-area__date--font
          =tweet.created_at.strftime("%m-%d")
    .category-area
      .category-area__btn
        .category-area__btn--kind 
          =tweet.category.name
        .category-area__btn--place 
          =tweet.place.name
      .category-area__store
        .category-area__store--font 
          =tweet.store

    .food-area
      .food-area__name
        =tweet.food
      .food-area__price
        =tweet.price
        %span 円
        
    .tweet-area
      =tweet.tweet



-# %ul.tweets-contener
-#   -@tweets.each do |tweet|
-#     %li.tweet-contener
-#       =link_to "","/tweets/#{tweet.id}", class: "link-btn"
-#       .avater-contener
-#         =link_to (image_tag "#{tweet.user.avater.url}", alt: "", class: "avater-size"), "/users/#{tweet.user_id}" 
-#       .contents-contener
-#         .contents-contener__user
-#           =link_to "#{tweet.user.name}", "/users/#{tweet.user_id}", class:"user-name" 
-#           .daytime
-#             =tweet.created_at.strftime("%Y-%m-%d %H:%M")
-#         .contents-contener__text
-#           =tweet.tweet
-#         .contents-contener__image
-#         -if tweet.image.url
-#           =link_to (image_tag tweet.image.url, alt: "", class: "image-size"), "#"
-#         .contents-contener__contents
-#           -if user_signed_in?
-#             .contents-contener__contents--likebtn-font
-#               -if tweet.like_by?(current_user)
-#                 =link_to tweet_likes_path(tweet.id), method: :delete do
-#                   =icon 'far', 'heart'
-#                   =tweet.likes.count
-#               -else
-#                 =link_to tweet_likes_path(tweet.id), method: :post do
-#                   =icon 'far', 'heart'
-#                   %font=tweet.likes.count
-#           -else
-#             .contents-contener__contents--likebtn-font
-#               =icon 'far', 'heart' 
-#               =tweet.likes.count 
-#           .contents-contener__contents--comment-font
-#             =icon 'far', 'comments', "#{tweet.comments.count}"

app/views/shared/_users.html.haml
%li.user-post
  =link_to "", user_path(user.id), class: "link-section" 
  .avater-section
    .avater-section__avater
      =link_to (image_tag "#{user.avater.url}", class: "avater-section__avater--size"), user_path(user.id)
      =link_to "#{user.name}", user_path(user.id), class: "avater-section__name"
    
  .profile-section
    .profile-section__follow
      -if user_signed_in? && user.id != current_user.id
        -if user.followed_by?(current_user)
          followed
        -else
          =link_to "follow", user_relationships_path(user.id), class: "profile-section__follow--font", method: :post 
    .profile-section__text
      =user.profile